databases:
  - name: ecommerce
    databaseName: ecommerce
    user: ecommerce

services:
  - type: web
    name: ecommerce
    env: python-3.10.12
    buildCommand: "./build.sh"
    startCommand: "gunicorn ecommerce.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False